name: Typescript Test
on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: npm/yarn/pnpm install
        uses: Jaid/action-npm-install@v1.2.4
      - name: tsc
        uses: icrawl/action-tsc@v1
